### ISSUE TITLE
Validation for add task form

### ISSUE THREAD

**Issue by SERPOVSKOY** [Tehnik-creator/Todo-List#3]
По нажатию на кнопку "Добавить задачу" проверять введенное значение

Если оно пусто, подсвечивать красным поле input

Если человек написал хотя бы одну букву в поле то убирать красную подсветку

_Подсказка: чтобы отслеживать изменения значения input читай [статью](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/change_event)_

**Comment by FRVALs** [comment]
Я смог сделать без статьи)
